[package]

name = "rfonts"
version = "0.0.1"
authors = ["Camille TJHOA <camille.tjhoa@gmail.com>"]

[dependencies]
hyper = "0.1.11"
getopts = "0.2.3"

[dependencies.cli]
git = "https://github.com/evnm/cli.rs"
